### ISSUE TITLE
Capture properties when indexing

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-catalog#10]
Metadata with additional properties not captured when indexed. 

Sample call on test instance: http://oam-catalog.herokuapp.com/meta?provider=UAViators. 

Test metadata json on s3: http://oam-test-node.s3.amazonaws.com/150411_efate_f1_Epao_1.tif_meta.json

cc @scisco

**Comment by scisco** [comment]
Fixed at e808af7fbdcf7a44313893b4a487474e024a0b90
