### ISSUE TITLE
Docs subdomain

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-catalog#42]
@cgiovando Can you add a `CNAME` record for `docs` to point to `hotosm.github.io`? 

We'll add a CNAME file to the catalog repo to create `docs.openaerialmap.org`. This will be the temp place for API docs. This can grow as additional documentation for any OAM piece.

**Comment by cgiovando** [comment]
Added

![screen shot 2015-07-30 at 10 21 57](https://cloud.githubusercontent.com/assets/10201533/8990084/da272c42-36a4-11e5-8da6-2189a133792a.png)
