### ISSUE TITLE
api subdomain

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-catalog#43]
@cgiovando Can you add a `CNAME` record for `api` to point to `oam-catalog.herokuapp.com`? We'll add the subdomain to create `api.openaerialmap.org` for the API.

**Comment by cgiovando** [comment]
Added

![screen shot 2015-07-30 at 10 22 54](https://cloud.githubusercontent.com/assets/10201533/8990104/fd654658-36a4-11e5-9f86-1462bde1d174.png)
