### ISSUE TITLE
POST parameters for new OIN/OAM sources

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-catalog#49]
Allow an (authenticated) user to manually post to the OAM catalog new sources added in an OIN store. This applies to the OAM QGIS plugin and OAM Uploader workflow. It will allow for validated new images to quickly appear in the catalog without having to wait for the worker app to harvest all OIN sources.

**Comment by smit1678** [comment]
Documentation for adding sources is here: http://docs.openaerialmap.org/#api-Meta-PostMeta. What kind of users do you see planning to use this function? If they're uploading to a bucket, it should be indexed within 10 mins. Right now the indexing is happening every 10 mins.

**Comment by smit1678** [comment]
Closing this out since there are current POST parameters. Current uploader does not use them and only pushes imagery into a bucket so there is a time delay of 5 mins now until it is indexed into the catalog. This time delay will be addressed when upload and catalog APIs are merged.
