### ISSUE TITLE
Analytics table not updated

### ISSUE THREAD

**Issue by jflasher** [hotosm/oam-catalog#66]
@smit1678 looked into this more and I am pretty sure what's happening is that there are so many files in the `hotosm-oam` bucket that the worker can't complete before it gets canceled by Heroku. So nothing gets written to the analytics collection. 

There are so many files in the bucket because we have logging turned on. We can either turn off logging or just move the logs to a different bucket. I didn't want to do this because wasn't sure why they had been turned on or if they were being used in any other system. I'm :100: - 1% sure that getting that `logs` dir out of the bucket will fix the issue.

**Comment by smit1678** [comment]
Good call on the debug. I turned off logging and moved nearly all of the files (still processing) to a dump bucket. Worker now runs without memory errors and seems to be running fine now. 

![1 heroku-cli 2016-03-29 09-52-13](https://cloud.githubusercontent.com/assets/796838/14102674/f175e538-f593-11e5-980b-d71bb0537c30.png)

For future reference, while there were still too many files in the bucket, I bumped up the Heroku dyno to have 2.5GB of memory and this solved the issue as well. It was able to process everything without error. I moved the dyno back down to `standard-1x`.
