### ISSUE TITLE
Dockerize oam-catalog 

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-catalog#84]
To make it easier for installing locally or on other cloud providers we need the oam-catalog app packaged along with dependencies (currently relying on Heroku addons `scheduler:standard`, `mongolab:shared-single-small` and `newrelic:wayne`).

CC @davidneudorfer @smit1678

**Comment by smit1678** [comment]
As a part of this we need to enable the use of `docker-compose` with a `docker-compose.yml` file.

**Comment by kamicut** [comment]
This is done in #92
