### ISSUE TITLE
Travis failing, bump node version?

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-catalog#88]
Travis tests fail upon linting errors. Testing this locally quick with a bump up of node from `v0.12` to `v4.5.x` removes these errors. 

@mojodna @danielfdsilva Any issues with bumping it up? Should be aiming for `v6.7`? 

```
/home/travis/build/hotosm/oam-catalog/node_modules/eslint/bin/eslint.js:16
const useStdIn = (process.argv.indexOf("--stdin") > -1),
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

https://travis-ci.org/hotosm/oam-catalog/builds/192644227

**Comment by mojodna** [comment]
Yes. The Node world has moved on and dependencies are starting to use newer JS features.

We should bump up to either 4.x (previous LTS) or 6.x (current LTS).

**Comment by nbumbarger** [comment]
@smit1678 Yes, as long as it builds under node 4.5.x, I don’t see any reason not to bump it.
